name: libbpf-ci

on: 
  pull_request:
  push:
  schedule:
    - cron:  '0 18 * * *'

jobs:
  vmtest:
    runs-on: ${{ matrix.runs_on }}
    name: Kernel ${{ matrix.kernel }} on ${{ matrix.runs_on }} + selftests
    strategy:
      fail-fast: false
      matrix:
        include:
          - kernel: 'LATEST'
            runs_on: ubuntu-20.04
            arch: 'x86_64'
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.github/actions/setup
        name: Setup
      - uses: ./.github/actions/vmtest
        name: vmtest
        with:
          kernel: ${{ matrix.kernel }}
          arch: ${{ matrix.arch }}
